# Generated by Django 4.0.3 on 2022-03-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('population', models.FloatField()),
                ('area', models.FloatField()),
                ('capital', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerImports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAndStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('area', models.FloatField()),
                ('quantity', models.FloatField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.commodity')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.county')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.commodity')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.county')),
            ],
        ),
    ]
