# Generated by Django 4.0.3 on 2022-03-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_alter_fertilizerimports_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerimports',
            old_name='date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='securityandstability',
            name='date',
        ),
        migrations.AddField(
            model_name='securityandstability',
            name='year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productions',
            name='year',
            field=models.FloatField(),
        ),
    ]
