# Generated by Django 4.0.3 on 2022-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_rename_date_fertilizerimports_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerimports',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productions',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityandstability',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
