# Generated by Django 4.0.3 on 2022-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_alter_fertilizerimports_year_alter_productions_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalexpenditure', models.FloatField()),
                ('agriculturespending', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='commodityprices',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='area',
            new_name='population_density',
        ),
        migrations.RenameField(
            model_name='productions',
            old_name='area',
            new_name='quantity_per_area',
        ),
        migrations.RemoveField(
            model_name='county',
            name='population',
        ),
        migrations.RemoveField(
            model_name='productions',
            name='quantity',
        ),
    ]
